# Generated by Django 6.0.3 on 2026-03-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='surname',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='poste',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
