# Generated by Django 5.1.4 on 2025-08-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
