# Generated by Django 6.0.3 on 2026-03-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0002_initial'),
        ('users', '0002_remove_customuser_surname_alter_customuser_poste'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='projets',
            field=models.ManyToManyField(blank=True, related_name='users', to='projets.projet'),
        ),
    ]
