# Generated by Django 5.1.4 on 2025-08-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_smsverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsverification',
            name='code',
            field=models.CharField(max_length=4),
        ),
    ]
