# Generated by Django 5.1.4 on 2025-08-27 11:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_smsverification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_modif',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profil',
            name='date_modif',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
