# Generated by Django 5.1.4 on 2025-09-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0004_stockitem'),
        ('users', '0007_customuser_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='projets',
            field=models.ManyToManyField(blank=True, related_name='users', to='projets.projet'),
        ),
    ]
