# Generated by Django 5.1.4 on 2025-10-13 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_projets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='id_profil',
            new_name='profil',
        ),
    ]
