# Generated by Django 5.1.4 on 2025-10-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_id_profil_customuser_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
    ]
