# Generated by Django 5.1.4 on 2025-10-07 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projets', '0005_projet_chef_chantier_projet_chef_projet_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('quantite', models.FloatField()),
                ('statut', models.CharField(choices=[('Emise', 'Émise'), ('Confirmée', 'Confirmée'), ('Approuvée', 'Approuvée'), ('Validée', 'Validée'), ('Livrée', 'Livrée')], max_length=50)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_emission', models.DateTimeField(null=True)),
                ('date_confirmation', models.DateTimeField(null=True)),
                ('date_approbation', models.DateTimeField(null=True)),
                ('date_validation', models.DateTimeField(null=True)),
                ('approve_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_approuvées', to=settings.AUTH_USER_MODEL)),
                ('confirme_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_confirmées', to=settings.AUTH_USER_MODEL)),
                ('emis_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_emises', to=settings.AUTH_USER_MODEL)),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projets.magasin')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projets.stockitem')),
                ('valide_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_validées', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
