# Generated by Django 6.0.3 on 2026-03-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=255, unique=True)),
                ('quantite_dem', models.FloatField()),
                ('raison', models.TextField()),
                ('statut', models.CharField(choices=[('Emise', 'Émise'), ('Confirmée', 'Confirmée'), ('Approuvée', 'Approuvée'), ('Validée', 'Validée'), ('Rejetée', 'Rejetée'), ('Livrée', 'Livrée')], max_length=50)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_emission', models.DateTimeField(null=True)),
                ('date_confirmation', models.DateTimeField(null=True)),
                ('commentaire_confirmation', models.TextField(blank=True, null=True)),
                ('date_approbation', models.DateTimeField(null=True)),
                ('commentaire_approbation', models.TextField(blank=True, null=True)),
                ('quantite_approuv', models.FloatField(blank=True, null=True)),
                ('date_validation', models.DateTimeField(null=True)),
                ('commentaire_validation', models.TextField(blank=True, null=True)),
                ('quantite_valid', models.FloatField(blank=True, null=True)),
                ('cout_total_approx', models.FloatField(blank=True, null=True)),
                ('is_valide', models.BooleanField(default=True)),
            ],
        ),
    ]
