# Generated by Django 5.1.4 on 2026-03-03 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demandes', '0001_initial'),
        ('projets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='approve_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_approuvées', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé ou non par'),
        ),
        migrations.AddField(
            model_name='demande',
            name='confirme_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_confirmées', to=settings.AUTH_USER_MODEL, verbose_name='Confirmé ou non par'),
        ),
        migrations.AddField(
            model_name='demande',
            name='emis_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_emises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demande',
            name='magasin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projets.magasin'),
        ),
        migrations.AddField(
            model_name='demande',
            name='stock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projets.stockitem'),
        ),
        migrations.AddField(
            model_name='demande',
            name='valide_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_validées', to=settings.AUTH_USER_MODEL, verbose_name='Validé ou non par'),
        ),
    ]
