# Generated by Django 5.1.4 on 2025-10-13 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='date_rejet',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='motif_rejet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='rejete_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_rejetées', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='demande',
            name='statut',
            field=models.CharField(choices=[('Emise', 'Émise'), ('Confirmée', 'Confirmée'), ('Approuvée', 'Approuvée'), ('Validée', 'Validée'), ('Rejetée', 'Rejetée'), ('Livrée', 'Livrée')], max_length=50),
        ),
    ]
