# Generated by Django 5.1.4 on 2025-10-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0002_demande_date_rejet_demande_motif_rejet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='raison',
            field=models.TextField(default='Pour les tests'),
            preserve_default=False,
        ),
    ]
