# Generated by Django 5.1.4 on 2026-03-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='is_valide',
            field=models.BooleanField(default=True),
        ),
    ]
