# Generated by Django 6.0.3 on 2026-03-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='is_quantity_reduced_by_approb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demande',
            name='is_quantity_reduced_by_valid',
            field=models.BooleanField(default=False),
        ),
    ]
