# Generated by Django 6.0.3 on 2026-03-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0003_demande_is_quantity_reduced_by_approb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='duree_traitement',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
