# Generated by Django 5.1.4 on 2025-10-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0003_demande_raison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='number',
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
    ]
