# Generated by Django 6.0.3 on 2026-03-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0004_demande_duree_traitement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='cout_total_approx',
            field=models.FloatField(blank=True, null=True, verbose_name='Coût total approximatif de la demande après approbation'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='duree_traitement',
            field=models.DurationField(blank=True, null=True, verbose_name='Durée de traitement de la demande'),
        ),
    ]
