# Generated by Django 5.1.4 on 2025-09-27 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projets', '0004_stockitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_m', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('objet', models.TextField()),
                ('nom_receveur', models.CharField(max_length=100)),
                ('tel_receveur', models.CharField(max_length=20)),
                ('fonction_receveur', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projets.magasin')),
                ('make_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declareur_entree', to=settings.AUTH_USER_MODEL)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projets.stockitem')),
            ],
        ),
        migrations.CreateModel(
            name='Entree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Livraison', 'Livraison'), ('Retour', 'Retour')], max_length=50)),
                ('quantite_m', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nom_deposant', models.CharField(max_length=100)),
                ('tel_deposant', models.CharField(max_length=20)),
                ('fonction_deposant', models.CharField(max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('societe', models.CharField(max_length=100)),
                ('tel_societe', models.CharField(max_length=20)),
                ('nom_livreur', models.CharField(max_length=100)),
                ('tel_livreur', models.CharField(max_length=20)),
                ('signature_livreur', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('is_active', models.BooleanField(default=True)),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projets.magasin')),
                ('make_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declareur_sortie', to=settings.AUTH_USER_MODEL)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projets.stockitem')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mouvements.sortie')),
            ],
        ),
    ]
