# Generated by Django 6.0.3 on 2026-03-05 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demandes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_m', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_creation', models.DateTimeField()),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('objet', models.TextField()),
                ('nom_receveur', models.CharField(max_length=100)),
                ('tel_receveur', models.CharField(max_length=20)),
                ('fonction_receveur', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Livraison', 'Livraison'), ('Retour', 'Retour')], max_length=50)),
                ('quantite_m', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nom_deposant', models.CharField(blank=True, max_length=100, null=True)),
                ('tel_deposant', models.CharField(blank=True, max_length=20, null=True)),
                ('fonction_deposant', models.CharField(blank=True, max_length=100, null=True)),
                ('date_creation', models.DateTimeField()),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('societe', models.CharField(blank=True, max_length=100, null=True)),
                ('tel_societe', models.CharField(blank=True, max_length=20, null=True)),
                ('nom_livreur', models.CharField(blank=True, max_length=100, null=True)),
                ('tel_livreur', models.CharField(blank=True, max_length=20, null=True)),
                ('signature_livreur', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('is_active', models.BooleanField(default=True)),
                ('demande_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demandes.demande')),
            ],
        ),
    ]
