# Generated by Django 5.1.4 on 2025-10-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mouvements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entree',
            name='fonction_deposant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entree',
            name='nom_deposant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entree',
            name='nom_livreur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entree',
            name='societe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entree',
            name='tel_deposant',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='entree',
            name='tel_livreur',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='entree',
            name='tel_societe',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
