# Generated by Django 5.1.4 on 2026-03-03 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mouvements', '0002_initial'),
        ('projets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entree',
            name='make_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declareur_sortie', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entree',
            name='stock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projets.stockitem'),
        ),
        migrations.AddField(
            model_name='sortie',
            name='magasin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projets.magasin'),
        ),
        migrations.AddField(
            model_name='sortie',
            name='make_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declareur_entree', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sortie',
            name='stock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projets.stockitem'),
        ),
        migrations.AddField(
            model_name='entree',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mouvements.sortie'),
        ),
    ]
