# Generated by Django 5.1.4 on 2025-10-17 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0004_alter_demande_number'),
        ('mouvements', '0002_alter_entree_fonction_deposant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entree',
            name='demande_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demandes.demande'),
        ),
    ]
