# Generated by Django 5.1.4 on 2025-11-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mouvements', '0003_entree_demande_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entree',
            name='date_creation',
            field=models.DateTimeField(),
        ),
    ]
