# Generated by Django 5.1.4 on 2025-11-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mouvements', '0004_alter_entree_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortie',
            name='date_creation',
            field=models.DateTimeField(),
        ),
    ]
