# Generated by Django 5.1.4 on 2025-11-20 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mouvements', '0005_alter_sortie_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entree',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
