# Generated by Django 5.1.4 on 2025-08-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0002_alter_magasin_creator_alter_projet_comptes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetphoto',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
