# Generated by Django 5.1.4 on 2025-08-27 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0003_projetphoto_is_active'),
        ('stocks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantite_seuil', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('etat', models.CharField(choices=[('neuf', 'Neuf'), ('usagé', 'Usagé'), ('endommagé', 'Endommagé')], default='neuf', max_length=50)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('add_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajouteur_stock', to=settings.AUTH_USER_MODEL)),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='projets.magasin')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='stocks.produit')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modificateur_stock', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('produit', 'magasin')},
            },
        ),
    ]
