# Generated by Django 5.1.4 on 2025-10-03 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0004_stockitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='chef_chantier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chef_chantier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projet',
            name='chef_projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chef_de_projet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projet',
            name='magasinier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='magasinier_projet', to=settings.AUTH_USER_MODEL),
        ),
    ]
