# Generated by Django 5.1.4 on 2025-08-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200, unique=True)),
                ('type', models.CharField(choices=[('materiel', 'Matériel'), ('materiau', 'Matériau')], max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('unite', models.CharField(choices=[('litre', 'Litre'), ('kg', 'Kilogramme'), ('m3', 'Mètre cube'), ('unite', 'Unité'), ('m', 'Mètre'), ('autre', 'Autre')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
